### ISSUE TITLE
User agents should delete the attribute rather than empty it

### ISSUE THREAD

**Issue by FremyCompany** [WICG/display-locking#78]
I don't think the empty string should mean the same as if the attribute wasn't present. It should probably be the same as "activatable" because that seems like a reasonable default. Authors can remove the attribute if they want to trigger the render.

Reasoning: setting up a background as a placeholder is easier if you can write

```css
element[SkipContentRender] {
    background: url(placeholder.png);
}
```

If an empty value does the same thing as no attribute, there is no single selector that will match both cases. Like you would need `:matches(:not([rendersubtree]), [rendersubtree=''])`.
